---
- name: Configure RSVP on Cisco XR router
  hosts: vxr_routers
  gather_facts: false
  tasks:

    - name: Configure RSVP
      cisco.iosxr.iosxr_config:
        src: templates/rsvp_config.j2
        backup: no