hostname_vxrs:
  VXR1: VXR1
  VXR2: VXR2
  VXR3: VXR3
  VXR4: VXR4
  VXR5: VXR5
  VXR6: VXR6

loopback_ips_v4:
  VXR1: 30.30.30.1
  VXR2: 30.30.30.2
  VXR3: 30.30.30.3
  VXR4: 30.30.30.4
  VXR5: 30.30.30.5
  VXR6: 30.30.30.6
  SRPCE: 192.168.30.57

loopback_ips_v6:
  VXR1: 2024::1
  VXR2: 2024::2
  VXR3: 2024::3
  VXR4: 2024::4
  VXR5: 2024::5
  VXR6: 2024::6
  SRPCE: 2024::57

grpc_port: 57400

isis_router_tag:
  VXR1: 1
  VXR2: 1
  VXR3: 1
  VXR4: 1
  VXR5: 1
  VXR6: 1
  SRPCE: 1

isis_net_id:
  VXR1: 49.0010.0100.0001.00
  VXR2: 49.0010.0100.0002.00
  VXR3: 49.0010.0100.0003.00
  VXR4: 49.0010.0100.0004.00
  VXR5: 49.0010.0100.0005.00
  VXR6: 49.0010.0100.0006.00
  SRPCE: 49.0010.0100.0057.00

sr_abs_sid:
  VXR1: 16001
  VXR2: 16002
  VXR3: 16003
  VXR4: 16004
  VXR5: 16005
  VXR6: 16006

sr_stc_abs_sid:
  VXR1: 17001
  VXR2: 17002
  VXR3: 17003
  VXR4: 17004
  VXR5: 17005
  VXR6: 17006

isis_interfaces:
  VXR1:
    - name: GigabitEthernet0/0/0/0
      is_flex_algo: 1
      fles_algo_affinity: top
    - name: GigabitEthernet0/0/0/1
      is_flex_algo: 1
      fles_algo_affinity: bottom
    - name: GigabitEthernet0/0/0/2
      is_flex_algo: 0
      fles_algo_affinity: NA
  VXR2:
    - name: GigabitEthernet0/0/0/0
      is_flex_algo: 1
      fles_algo_affinity: top
    - name: GigabitEthernet0/0/0/1
      is_flex_algo: 0
      fles_algo_affinity: NA
    - name: GigabitEthernet0/0/0/2
      is_flex_algo: 1
      fles_algo_affinity: top
  VXR3:
    - name: GigabitEthernet0/0/0/0
      is_flex_algo: 1
      fles_algo_affinity: bottom
    - name: GigabitEthernet0/0/0/1
      is_flex_algo: 0
      fles_algo_affinity: NA
    - name: GigabitEthernet0/0/0/2
      is_flex_algo: 1
      fles_algo_affinity: bottom
  VXR4:
    - name: GigabitEthernet0/0/0/0
      is_flex_algo: 1
      fles_algo_affinity: top
    - name: GigabitEthernet0/0/0/1
      is_flex_algo: 0
      fles_algo_affinity: NA
    - name: GigabitEthernet0/0/0/2
      is_flex_algo: 1
      fles_algo_affinity: top
  VXR5:
    - name: GigabitEthernet0/0/0/0
      is_flex_algo: 1
      fles_algo_affinity: bottom
    - name: GigabitEthernet0/0/0/1
      is_flex_algo: 0
      fles_algo_affinity: NA
    - name: GigabitEthernet0/0/0/2
      is_flex_algo: 1
      fles_algo_affinity: bottom
  VXR6:
    - name: GigabitEthernet0/0/0/0
      is_flex_algo: 1
      fles_algo_affinity: top
    - name: GigabitEthernet0/0/0/1
      is_flex_algo: 1
      fles_algo_affinity: bottom
  SRPCE:
    - name: GigabitEthernet0/0/0/0
      is_flex_algo: no
      fles_algo_affinity: NA

rsvp_interfaces:
  VXR1:
    - name: GigabitEthernet0/0/0/0
      bw_percent: 100
    - name: GigabitEthernet0/0/0/1
      bw_percent: 100
  VXR2:
    - name: GigabitEthernet0/0/0/0
      bw_percent: 100
    - name: GigabitEthernet0/0/0/1
      bw_percent: 100
    - name: GigabitEthernet0/0/0/2
      bw_percent: 100
  VXR3:
    - name: GigabitEthernet0/0/0/0
      bw_percent: 100
    - name: GigabitEthernet0/0/0/1
      bw_percent: 100
    - name: GigabitEthernet0/0/0/2
      bw_percent: 100
  VXR4:
    - name: GigabitEthernet0/0/0/0
      bw_percent: 100
    - name: GigabitEthernet0/0/0/1
      bw_percent: 100
    - name: GigabitEthernet0/0/0/2
      bw_percent: 100
  VXR5:
    - name: GigabitEthernet0/0/0/0
      bw_percent: 100
    - name: GigabitEthernet0/0/0/1
      bw_percent: 100
    - name: GigabitEthernet0/0/0/2
      bw_percent: 100
  VXR6:
    - name: GigabitEthernet0/0/0/0
      bw_percent: 100
    - name: GigabitEthernet0/0/0/1
      bw_percent: 100

mpls_interfaces:
  VXR1:
    - name: GigabitEthernet0/0/0/0
      attribute-names: RED
      admin-weight: 10
    - name: GigabitEthernet0/0/0/1
      attribute-names: RED
      admin-weight: 10
  VXR2:
    - name: GigabitEthernet0/0/0/0
      attribute-names: RED
      admin-weight: 10
    - name: GigabitEthernet0/0/0/1
      attribute-names: RED
      admin-weight: 10
    - name: GigabitEthernet0/0/0/2
      attribute-names: RED
      admin-weight: 10
  VXR3:
    - name: GigabitEthernet0/0/0/0
      attribute-names: RED
      admin-weight: 10
    - name: GigabitEthernet0/0/0/1
      attribute-names: RED
      admin-weight: 10
    - name: GigabitEthernet0/0/0/2
      attribute-names: RED
      admin-weight: 10
  VXR4:
    - name: GigabitEthernet0/0/0/0
      attribute-names: RED
      admin-weight: 10
    - name: GigabitEthernet0/0/0/1
      attribute-names: RED
      admin-weight: 10
    - name: GigabitEthernet0/0/0/2
      attribute-names: RED
      admin-weight: 10
  VXR5:
    - name: GigabitEthernet0/0/0/0
      attribute-names: RED
      admin-weight: 10
    - name: GigabitEthernet0/0/0/1
      attribute-names: RED
      admin-weight: 10
    - name: GigabitEthernet0/0/0/2
      attribute-names: RED
      admin-weight: 10
  VXR6:
    - name: GigabitEthernet0/0/0/0
      attribute-names: RED
      admin-weight: 10
    - name: GigabitEthernet0/0/0/1
      attribute-names: RED
      admin-weight: 10

pce_server_1: 192.168.30.57
pce_p2p_intf: GigabitEthernet0/0/0/0
pce_p2p_ipv4: 172.16.1.13/24
pce_p2p_ipv6: 2001:db8:100::2/64

rsvp_loopback_ips_v4:
  VXR1: 50.50.50.1
  VXR2: 50.50.50.2
  VXR3: 50.50.50.3
  VXR4: 50.50.50.4
  VXR5: 50.50.50.5
  VXR6: 50.50.50.6

rsvp_loopback_ips_v6:
  VXR1: 2024::11
  VXR2: 2024::22
  VXR3: 2024::33
  VXR4: 2024::44
  VXR5: 2024::55
  VXR6: 2024::66

srv6_prefix:
  VXR1: 
      TOP:  fcbb:2:1::/48
      MAIN: fcbb:0:1::/48
      BOTTOM: fcbb:3:1::/48
      LATENCY: fcbb:1:1::/48
  VXR2:  
      TOP:  fcbb:2:2::/48
      MAIN: fcbb:0:2::/48
      BOTTOM: fcbb:3:2::/48
      LATENCY: fcbb:1:2::/48
  VXR3:  
      TOP:  fcbb:2:3::/48
      MAIN: fcbb:0:3::/48
      BOTTOM: fcbb:3:3::/48
      LATENCY: fcbb:1:3::/48
  VXR4:  
      TOP:  fcbb:2:4::/48
      MAIN: fcbb:0:4::/48
      BOTTOM: fcbb:3:4::/48
      LATENCY: fcbb:1:4::/48
  VXR5:  
      TOP:  fcbb:2:5::/48
      MAIN: fcbb:0:5::/48
      BOTTOM: fcbb:3:5::/48
      LATENCY: fcbb:1:5::/48
  VXR6:  
      TOP:  fcbb:2:6::/48
      MAIN: fcbb:0:6::/48
      BOTTOM: fcbb:3:6::/48
      LATENCY: fcbb:1:6::/48